### PR TITLE
Update to 1.19.3, 1.19.4

### PR DESCRIPTION
**Pull request by MeeniMc**
Updated to 1.19.3
fixes: #4 
fixes: #3

### CODE REVIEW

**Comment by MeeniMc** [comment]
Still around @DanikingRD ?

**Comment by DanikingRD** [comment]
Sorry, i've been very busy lately. I'll test it out and merge it whenever i can. Thanks for contributing

**Comment by MeeniMc** [comment]
I recommend you still publish 1.19.3 (first commit) and then publish 1.19.4

ATM I couldn't test LambDynamicLight integration on 1.19.4 because that mod has not updated yet, but I expect it to work as-is.

**Comment by MeeniMc** [comment]
Follow-up on this discussion, there is indeed no problem with  LambDynamicLight, it works as intended.

**Pull request merged**
